Integration test workflow
Azure-Samples/piggymetrics pull request #13
Opened 2023-11-15 09:42 UTC by majguo

## Summary

The PR includes the following major changes:

* Add one workflow **Integration test** `integ-test.yaml` by leveraging `docker-compose`
* Run additional integration test for the existing workflow **Setup demo**
* Run additional integration test for the existing workflow **Rolling update**
* Setup Elastic/Kibana/Filebeat containers in `docker-compose`

## Testing

New/updated workflows ran successfully in my fork:

* [Integration test](https://github.com/majguo/piggymetrics/actions/runs/6859427692)
* [Setup demo](https://github.com/majguo/piggymetrics/actions/runs/6858525476): integration test is bypassed as gateway is not accessible if the app is deployed using internal sub
* [Setup demo](https://github.com/majguo/piggymetrics/actions/runs/6858153729): integration test is executed
* [Rolling update](https://github.com/majguo/piggymetrics/actions/runs/6858631593): integration test is bypassed as gateway is not accessible if the app is deployed using internal sub
* [Rolling update](https://github.com/majguo/piggymetrics/actions/runs/6858413875): integration test is executed

Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

2023-12-07 21:55 UTC, edburns commented on README.md
> +./build.sh $KEYSTORE_PASSWORD $IMAGE_TAG ${NGINX_VERSION} ${OTEL_MODULE_VERSION} $REGISTRY_NAME
I find `build.sh` is too small a name for what it does. I suggest renaming `build.sh`  to something more accurate, such as `build-piggymetrics-microservices.sh`. What do you think?

2023-12-07 21:56 UTC, edburns commented on build.sh
>  #!/bin/bash
See my comment on `README.md` about "I find `build.sh` is too small a name".

2023-12-07 21:59 UTC, edburns requested changes
See comment on `README.md` and `build.sh`.

2023-12-07 23:18 UTC, majguo commented on README.md
> +./build.sh $KEYSTORE_PASSWORD $IMAGE_TAG ${NGINX_VERSION} ${OTEL_MODULE_VERSION} $REGISTRY_NAME
Good suggestion, but I prefer a shorter name, such as `build-piggymetrics.sh`.

2023-12-07 23:31 UTC, majguo commented on build.sh
>  #!/bin/bash
Addressed in [rename to build-piggymetrics.sh](https://github.com/Azure-Samples/piggymetrics/pull/13/commits/4d324c6b6f074b2600bcafc67d5495c417ecc22e).

2023-12-08 00:28 UTC, edburns approved these changes

2023-12-08 00:41 UTC, merged